package suggest

var gitSubcommands = []Suggestion{
	{
		Value:       "status",
		Description: "Show the working tree status.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "add",
		Description: "Add file changes to the staging area.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "commit",
		Description: "Record staged changes in repository history.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "branch",
		Description: "List, create, or delete branches.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "switch",
		Description: "Switch branches or create a new branch.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "checkout",
		Description: "Switch branches or restore working tree files.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "restore",
		Description: "Restore working tree files.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "log",
		Description: "Show commit history.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "diff",
		Description: "Show changes between commits and working trees.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "merge",
		Description: "Join development histories together.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "rebase",
		Description: "Reapply commits on top of another base.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "fetch",
		Description: "Download objects and refs from a remote.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "pull",
		Description: "Fetch and integrate changes from a remote.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "push",
		Description: "Update remote refs and transfer objects.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "stash",
		Description: "Temporarily store uncommitted changes.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "clone",
		Description: "Clone a repository into a new directory.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "init",
		Description: "Create an empty Git repository.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "remote",
		Description: "Manage tracked remote repositories.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "tag",
		Description: "Create, list, delete, or verify tags.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "reset",
		Description: "Reset the current HEAD to a specified state.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "revert",
		Description: "Create commits that reverse earlier commits.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "cherry-pick",
		Description: "Apply changes introduced by existing commits.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "clean",
		Description: "Remove untracked files from the working tree.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "rm",
		Description: "Remove files from the working tree and index.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "mv",
		Description: "Move or rename files, directories, or symbolic links.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "worktree",
		Description: "Manage multiple working trees attached to a repository.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "submodule",
		Description: "Manage repositories embedded inside another repository.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "bisect",
		Description: "Find the commit that introduced a bug using binary search.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "show",
		Description: "Show commits, tags, trees, or other Git objects.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "blame",
		Description: "Show which commit and author last modified each line.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "grep",
		Description: "Search tracked files for lines matching a pattern.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "shortlog",
		Description: "Summarize commit history grouped by author.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "describe",
		Description: "Give an object a human-readable name based on a ref.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "reflog",
		Description: "Manage the history of updates to references.",
		Kind:        KindSubcommand,
	},
}

var gitNestedSubcommands = map[string][]Suggestion{
	"remote": {
		{
			Value:       "add",
			Description: "Add a new remote repository.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "rename",
			Description: "Rename an existing remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "remove",
			Description: "Remove an existing remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "set-head",
			Description: "Set or delete the default branch for a remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "set-branches",
			Description: "Change the branches tracked for a remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "get-url",
			Description: "Show the URL of a remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "set-url",
			Description: "Change the URL of a remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "show",
			Description: "Show information about a remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "prune",
			Description: "Delete stale remote-tracking references.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "update",
			Description: "Fetch updates for one or more remotes.",
			Kind:        KindSubcommand,
		},
	},
	"worktree": {
		{
			Value:       "add",
			Description: "Create a new working tree.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "list",
			Description: "List working trees attached to the repository.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "lock",
			Description: "Prevent a working tree from being pruned.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "move",
			Description: "Move a working tree to another location.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "prune",
			Description: "Remove stale working tree metadata.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "remove",
			Description: "Remove an attached working tree.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "repair",
			Description: "Repair working tree administrative files.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "unlock",
			Description: "Unlock a previously locked working tree.",
			Kind:        KindSubcommand,
		},
	},
	"submodule": {
		{
			Value:       "add",
			Description: "Add another repository as a submodule.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "status",
			Description: "Show the status of submodules.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "init",
			Description: "Initialize submodules recorded in the index.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "deinit",
			Description: "Unregister selected submodules.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "update",
			Description: "Clone missing submodules and update their working trees.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "set-branch",
			Description: "Configure the branch tracked by a submodule.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "set-url",
			Description: "Change the URL of a submodule.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "summary",
			Description: "Show commit differences for submodules.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "foreach",
			Description: "Run a command in each checked-out submodule.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "sync",
			Description: "Synchronize submodule URLs with .gitmodules.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "absorbgitdirs",
			Description: "Move submodule Git directories into the parent repository.",
			Kind:        KindSubcommand,
		},
	},
	"bisect": {
		{
			Value:       "start",
			Description: "Begin a binary search session.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "good",
			Description: "Mark commits as known to be good.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "bad",
			Description: "Mark commits as known to be bad.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "terms",
			Description: "Show the terms used for good and bad commits.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "skip",
			Description: "Exclude commits that cannot be tested.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "next",
			Description: "Advance to the next commit selected by bisect.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "reset",
			Description: "End the bisect session and restore the previous branch.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "visualize",
			Description: "Show the commits remaining in the search.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "replay",
			Description: "Replay a bisect session from a log file.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "log",
			Description: "Show the decisions made during the bisect session.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "run",
			Description: "Automatically classify commits by running a command.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "new",
			Description: "Mark commits as containing the newer state.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "old",
			Description: "Mark commits as containing the older state.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "view",
			Description: "Show the commits remaining in the search.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "help",
			Description: "Show detailed bisect help.",
			Kind:        KindSubcommand,
		},
	},
	"reflog": {
		{
			Value:       "show",
			Description: "Show the reflog of a reference.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "list",
			Description: "List references that have a reflog.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "exists",
			Description: "Check whether a reference has a reflog.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "write",
			Description: "Append an entry to a reflog.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "delete",
			Description: "Delete selected entries from a reflog.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "drop",
			Description: "Remove the reflog for selected references.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "expire",
			Description: "Prune old entries from reflogs.",
			Kind:        KindSubcommand,
		},
	},
}

var gitOptions = map[string][]Suggestion{
	"branch": {
		{
			Value:       "--show-current",
			Description: "Print the name of the current branch.",
			Kind:        KindOption,
		},
		{
			Value:       "--merged",
			Description: "List branches already merged into the specified commit.",
			Kind:        KindOption,
		},
		{
			Value:       "--no-merged",
			Description: "List branches that have not been merged.",
			Kind:        KindOption,
		},
		{
			Value:       "--delete",
			Description: "Delete a branch.",
			Kind:        KindOption,
		},
	},
	"status": {
		{
			Value:       "--short",
			Description: "Show status in a compact format.",
			Kind:        KindOption,
		},
		{
			Value:       "--branch",
			Description: "Show branch information.",
			Kind:        KindOption,
		},
		{
			Value:       "--porcelain",
			Description: "Use a stable machine-readable format.",
			Kind:        KindOption,
		},
	},
	"add": {
		{
			Value:       "--all",
			Description: "Stage changes from the entire working tree.",
			Kind:        KindOption,
		},
		{
			Value:       "--patch",
			Description: "Interactively choose changes to stage.",
			Kind:        KindOption,
		},
		{
			Value:       "--update",
			Description: "Stage modified and deleted tracked files.",
			Kind:        KindOption,
		},
	},
	"commit": {
		{
			Value:            "--message",
			Description:      "Use the supplied text as the commit message; repeat it to add paragraphs.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "message",
			ValueDescription: "Enter the commit message. Quotes are recommended.",
			Repeatable:       true,
			Aliases:          []string{"-m"},
		},
		{
			Value:       "--amend",
			Description: "Replace the most recent commit.",
			Kind:        KindOption,
		},
		{
			Value:       "--all",
			Description: "Stage modified and deleted tracked files before committing.",
			Kind:        KindOption,
		},
		{
			Value:       "--no-verify",
			Description: "Skip commit hooks.",
			Kind:        KindOption,
		},
	},
	"switch": {
		{
			Value:       "--create",
			Description: "Create a new branch and switch to it.",
			Kind:        KindOption,
		},
		{
			Value:       "--detach",
			Description: "Switch to a commit without attaching HEAD to a branch.",
			Kind:        KindOption,
		},
	},
	"log": {
		{
			Value:       "--oneline",
			Description: "Show each commit on one line.",
			Kind:        KindOption,
		},
		{
			Value:       "--graph",
			Description: "Draw a text-based commit graph.",
			Kind:        KindOption,
		},
		{
			Value:       "--all",
			Description: "Show commits from all refs.",
			Kind:        KindOption,
		},
	},
	"clone": {
		{
			Value:            "--branch",
			Description:      "Check out the specified branch after cloning.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter the branch or tag to check out.",
			Aliases:          []string{"-b"},
		},
		{
			Value:            "--depth",
			Description:      "Create a shallow clone with limited history.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "depth",
			ValueDescription: "Enter the number of commits to include",
		},
		{
			Value:            "--origin",
			Description:      "Use a remote name other than origin.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "name",
			ValueDescription: "Enter the name of the remote.",
			Aliases:          []string{"-o"},
		},
		{
			Value:       "--single-branch",
			Description: "Clone only the history of one branch.",
			Kind:        KindOption,
		},
		{
			Value:       "--recurse-submodules",
			Description: "Initialize and clone submodules.",
			Kind:        KindOption,
		},
		{
			Value:       "--no-checkout",
			Description: "Do not checkout HEAD after cloning.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--bare",
			Description: "Create a bare repository.",
			Kind:        KindOption,
		},
		{
			Value:       "--mirror",
			Description: "Create a mirror of the source repository.",
			Kind:        KindOption,
		},
	},
	"init": {
		{
			Value:       "--bare",
			Description: "Create a bare repository.",
			Kind:        KindOption,
		},
		{
			Value:            "--initial-branch",
			Description:      "Use the specified name for the initial branch.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter the name of the initial branch.",
			Aliases:          []string{"-b"},
		},
		{
			Value:            "--template",
			Description:      "Use templates from the specified directory.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "directory",
			ValueDescription: "Enter the template directory.",
		},
		{
			Value:            "--separate-git-dir",
			Description:      "Store repository metadata in a separate directory.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "git-dir",
			ValueDescription: "Enter the Git metadata directory.",
		},
	},
	"remote": {
		{
			Value:       "--verbose",
			Description: "Show remote URLs in addition to remote names",
			Kind:        KindOption,
			Aliases:     []string{"-v"},
		},
	},
	"remote add": {
		{
			Value:       "-f",
			Description: "Fetch the remote immediately after adding it.",
			Kind:        KindOption,
		},
		{
			Value:            "-t",
			Description:      "Track only the specified branch; repeat it to track multiple branches.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter a remote branch to track.",
			Repeatable:       true,
		},
		{
			Value:            "-m",
			Description:      "Set the remote's default branch.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter the remote's default branch.",
		},
		{
			Value:         "--tags",
			Description:   "Import every tag from the remote.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-tags"},
		},
		{
			Value:         "--no-tags",
			Description:   "Do not import tags from the remote.",
			Kind:          KindOption,
			ConflictsWith: []string{"--tags"},
		},
		{
			Value:       "--mirror=",
			Description: "Create a fetch or push mirror; append fetch or push.",
			Kind:        KindOption,
		},
	},
	"remote rename": {
		{
			Value:         "--progress",
			Description:   "Show progress while renaming remote references.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-progress"},
		},
		{
			Value:         "--no-progress",
			Description:   "Do not show progress while renaming remote references.",
			Kind:          KindOption,
			ConflictsWith: []string{"--progress"},
		},
	},
	"remote set-head": {
		{
			Value:         "--auto",
			Description:   "Query the remote and set its default branch automatically.",
			Kind:          KindOption,
			Aliases:       []string{"-a"},
			ConflictsWith: []string{"--delete"},
		},
		{
			Value:         "--delete",
			Description:   "Delete the remote's default-branch reference.",
			Kind:          KindOption,
			Aliases:       []string{"-d"},
			ConflictsWith: []string{"--auto"},
		},
	},
	"remote set-branches": {
		{
			Value:       "--add",
			Description: "Add branches instead of replacing the tracked branch list.",
			Kind:        KindOption,
		},
	},
	"remote get-url": {
		{
			Value:       "--push",
			Description: "Show push URLs instead of fetch URLs.",
			Kind:        KindOption,
		},
		{
			Value:       "--all",
			Description: "Show all URLs for the remote.",
			Kind:        KindOption,
		},
	},
	"remote set-url": {
		{
			Value:       "--push",
			Description: "Change push URLs instead of fetch URLs.",
			Kind:        KindOption,
		},
		{
			Value:         "--add",
			Description:   "Add a new URL instead of replacing an existing URL.",
			Kind:          KindOption,
			ConflictsWith: []string{"--delete"},
		},
		{
			Value:         "--delete",
			Description:   "Delete URLs matching the supplied regular expression.",
			Kind:          KindOption,
			ConflictsWith: []string{"--add"},
		},
	},
	"remote show": {
		{
			Value:       "--no-query",
			Description: "Use cached information without querying the remote.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
	},
	"remote prune": {
		{
			Value:       "--dry-run",
			Description: "Report stale references without deleting them.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
	},
	"remote update": {
		{
			Value:       "--prune",
			Description: "Prune stale references while updating remotes.",
			Kind:        KindOption,
			Aliases:     []string{"-p"},
		},
	},
	"tag": {
		{
			Value:       "--list",
			Description: "List tags, optionally matching a pattern",
			Kind:        KindOption,
			Aliases:     []string{"-l"},
		},
		{
			Value:       "--annotate",
			Description: "Create an annotated tag.",
			Kind:        KindOption,
			Aliases:     []string{"-a"},
		},
		{
			Value:            "--message",
			Description:      "Use the supplied annotation message.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "message",
			ValueDescription: "Enter the tag annotation message.",
			Repeatable:       true,
			Aliases:          []string{"-m"},
		},
		{
			Value:       "--delete",
			Description: "Delete one or more tags.",
			Kind:        KindOption,
			Aliases:     []string{"-d"},
		},
		{
			Value:       "--force",
			Description: "Replace an existing tag.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "--sign",
			Description: "Create a GPG-signed tag",
			Kind:        KindOption,
			Aliases:     []string{"-s"},
		},
		{
			Value:       "--verify",
			Description: "Verify the GPG signature of a tag",
			Kind:        KindOption,
			Aliases:     []string{"-v"},
		},
		{
			Value:            "--contains",
			Description:      "List tags containing the specified commit.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "commit",
			ValueDescription: "Enter a commit or revision",
		},
		{
			Value:            "--points-at",
			Description:      "List tags pointing at the specified object.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "object",
			ValueDescription: "Enter a Git object name.",
		},
	},
	"reset": {
		{
			Value:         "--soft",
			Description:   "Reset HEAD only; keep the index and working tree unchanged.",
			Kind:          KindOption,
			ConflictsWith: []string{"--mixed", "--hard", "--merge", "--keep", "--patch"},
		},
		{
			Value:         "--mixed",
			Description:   "Reset HEAD and the index, but keep working tree changes.",
			Kind:          KindOption,
			ConflictsWith: []string{"--soft", "--hard", "--merge", "--keep", "--patch"},
		},
		{
			Value:         "--hard",
			Description:   "Reset HEAD, index, and working tree; uncommitted changes may be lost.",
			Kind:          KindOption,
			ConflictsWith: []string{"--soft", "--mixed", "--merge", "--keep", "--patch"},
		},
		{
			Value:         "--merge",
			Description:   "Reset the index and update files while preserving unmerged changes.",
			Kind:          KindOption,
			ConflictsWith: []string{"--soft", "--mixed", "--hard", "--keep", "--patch"},
		},
		{
			Value:         "--keep",
			Description:   "Reset HEAD while preserving local working tree changes.",
			Kind:          KindOption,
			ConflictsWith: []string{"--soft", "--mixed", "--hard", "--merge", "--patch"},
		},
		{
			Value:         "--patch",
			Description:   "Interactively select changes to reset.",
			Kind:          KindOption,
			Aliases:       []string{"-p"},
			ConflictsWith: []string{"--soft", "--mixed", "--hard", "--merge", "--keep"},
		},
		{
			Value:       "--quiet",
			Description: "Only report errors.",
			Kind:        KindOption,
			Aliases:     []string{"-q"},
		},
		{
			Value:       "--no-refresh",
			Description: "Do not refresh the index after resetting.",
			Kind:        KindOption,
		},
		{
			Value:            "--pathspec-from-file",
			Description:      "Read pathspec entries from a file.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "file",
			ValueDescription: "Enter a file containing pathspec entries.",
		},
		{
			Value:       "--pathspec-file-nul",
			Description: "Separate pathspec entries with NUL characters.",
			Kind:        KindOption,
		},
	},
	"revert": {
		{
			Value:       "--no-commit",
			Description: "Apply the inverse changes without creating a commit.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:         "--edit",
			Description:   "Edit the revert commit message before committing.",
			Kind:          KindOption,
			Aliases:       []string{"-e"},
			ConflictsWith: []string{"--no-edit"},
		},
		{
			Value:         "--no-edit",
			Description:   "Use the generated commit message without opening an editor.",
			Kind:          KindOption,
			ConflictsWith: []string{"--edit"},
		},
		{
			Value:            "--mainline",
			Description:      "Select the parent used when reverting a merge commit.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "parent-number",
			ValueDescription: "Enter the mainline parent number, usually 1 or 2.",
			Aliases:          []string{"-m"},
		},
		{
			Value:       "--signoff",
			Description: "Add a Signed-off-by trailer to the commit message.",
			Kind:        KindOption,
			Aliases:     []string{"-s"},
		},
		{
			Value:            "--strategy",
			Description:      "Use the specified merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "strategy",
			ValueDescription: "Enter a merge strategy.",
		},
		{
			Value:            "--strategy-option",
			Description:      "Pass an option to the selected merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "option",
			ValueDescription: "Enter a merge strategy option.",
			Repeatable:       true,
			Aliases:          []string{"-X"},
		},
		{
			Value:         "--continue",
			Description:   "Continue after resolving conflicts.",
			Kind:          KindOption,
			ConflictsWith: []string{"--skip", "--abort", "--quit"},
		},
		{
			Value:         "--skip",
			Description:   "Skip the current commit and continue.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--abort", "--quit"},
		},
		{
			Value:         "--abort",
			Description:   "Cancel the operation and restore the previous state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--quit"},
		},
		{
			Value:         "--quit",
			Description:   "Stop the operation without restoring the previous state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--abort"},
		},
	},
	"cherry-pick": {
		{
			Value:       "--no-commit",
			Description: "Apply changes without creating a commit.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:         "--edit",
			Description:   "Edit the commit message before committing.",
			Kind:          KindOption,
			Aliases:       []string{"-e"},
			ConflictsWith: []string{"--no-edit"},
		},
		{
			Value:         "--no-edit",
			Description:   "Use the original commit message without opening an editor.",
			Kind:          KindOption,
			ConflictsWith: []string{"--edit"},
		},
		{
			Value:            "--mainline",
			Description:      "Select the parent used when cherry-picking a merge commit.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "parent-number",
			ValueDescription: "Enter the mainline parent number, usually 1 or 2.",
			Aliases:          []string{"-m"},
		},
		{
			Value:       "--signoff",
			Description: "Add a Signed-off-by trailer to the commit message.",
			Kind:        KindOption,
			Aliases:     []string{"-s"},
		},
		{
			Value:            "--strategy",
			Description:      "Use the specified merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "strategy",
			ValueDescription: "Enter a merge strategy.",
		},
		{
			Value:            "--strategy-option",
			Description:      "Pass an option to the selected merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "option",
			ValueDescription: "Enter a merge strategy option.",
			Repeatable:       true,
			Aliases:          []string{"-X"},
		},
		{
			Value:       "-x",
			Description: "Append the original commit name to the commit message.",
			Kind:        KindOption,
		},
		{
			Value:       "--ff",
			Description: "Allow a fast-forward when possible.",
			Kind:        KindOption,
		},
		{
			Value:            "--empty",
			Description:      "Choose how commits that become empty are handled.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "mode",
			ValueDescription: "Enter stop, drop, or keep.",
		},
		{
			Value:         "--continue",
			Description:   "Continue after resolving conflicts.",
			Kind:          KindOption,
			ConflictsWith: []string{"--skip", "--abort", "--quit"},
		},
		{
			Value:         "--skip",
			Description:   "Skip the current commit and continue.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--abort", "--quit"},
		},
		{
			Value:         "--abort",
			Description:   "Cancel the operation and restore the previous state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--quit"},
		},
		{
			Value:         "--quit",
			Description:   "Stop the operation without restoring the previous state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--abort"},
		},
	},
	"clean": {
		{
			Value:       "--quiet",
			Description: "Do not print the names of removed files.",
			Kind:        KindOption,
			Aliases:     []string{"-q"},
		},
		{
			Value:       "--dry-run",
			Description: "Show what would be removed without deleting anything.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--force",
			Description: "Allow removal of untracked files.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "--interactive",
			Description: "Interactively choose files to remove.",
			Kind:        KindOption,
			Aliases:     []string{"-i"},
		},
		{
			Value:       "-d",
			Description: "Remove untracked directories in addition to files.",
			Kind:        KindOption,
		},
		{
			Value:            "--exclude",
			Description:      "Add a pattern to the ignore rules used by clean.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "pattern",
			ValueDescription: "Enter a pattern that should not be removed.",
			Repeatable:       true,
			Aliases:          []string{"-e"},
		},
		{
			Value:         "-x",
			Description:   "Remove ignored files as well as untracked files.",
			Kind:          KindOption,
			ConflictsWith: []string{"-X"},
		},
		{
			Value:         "-X",
			Description:   "Remove only ignored files.",
			Kind:          KindOption,
			ConflictsWith: []string{"-x"},
		},
	},
	"rm": {
		{
			Value:       "--dry-run",
			Description: "Show files that would be removed without removing them.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--quiet",
			Description: "Do not print the names of removed files.",
			Kind:        KindOption,
			Aliases:     []string{"-q"},
		},
		{
			Value:       "--cached",
			Description: "Remove paths only from the index and keep working tree files.",
			Kind:        KindOption,
		},
		{
			Value:       "--force",
			Description: "Override the up-to-date check.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "-r",
			Description: "Allow recursive removal of directories.",
			Kind:        KindOption,
		},
		{
			Value:       "--ignore-unmatch",
			Description: "Exit successfully even when no path matches.",
			Kind:        KindOption,
		},
		{
			Value:       "--sparse",
			Description: "Allow updating entries outside the sparse-checkout cone.",
			Kind:        KindOption,
		},
		{
			Value:            "--pathspec-from-file",
			Description:      "Read pathspec entries from a file.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "file",
			ValueDescription: "Enter a file containing pathspec entries.",
		},
		{
			Value:       "--pathspec-file-nul",
			Description: "Separate pathspec entries with NUL characters.",
			Kind:        KindOption,
		},
	},
	"mv": {
		{
			Value:       "--verbose",
			Description: "Print the names of files as they are moved.",
			Kind:        KindOption,
			Aliases:     []string{"-v"},
		},
		{
			Value:       "--dry-run",
			Description: "Show what would be moved without changing files.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--force",
			Description: "Allow an existing destination to be overwritten.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "-k",
			Description: "Skip paths that cannot be moved or renamed.",
			Kind:        KindOption,
		},
		{
			Value:       "--sparse",
			Description: "Allow updating entries outside the sparse-checkout cone.",
			Kind:        KindOption,
		},
	},
	"rebase": {
		{
			Value:            "--onto",
			Description:      "Rebase commits onto a different base.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "revision",
			ValueDescription: "Enter the new base branch, tag, or commit.",
			ConflictsWith:    []string{"--keep-base"},
		},
		{
			Value:         "--keep-base",
			Description:   "Use the merge base of upstream and branch as the base.",
			Kind:          KindOption,
			ConflictsWith: []string{"--onto", "--root"},
		},
		{
			Value:         "--interactive",
			Description:   "Edit the list of commits before rebasing.",
			Kind:          KindOption,
			Aliases:       []string{"-i"},
			ConflictsWith: []string{"--apply"},
		},
		{
			Value:            "--exec",
			Description:      "Run a command after each rebased commit.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "command",
			ValueDescription: "Enter the shell command to execute.",
			Repeatable:       true,
			Aliases:          []string{"-x"},
			ConflictsWith:    []string{"--apply"},
		},
		{
			Value:         "--autosquash",
			Description:   "Reorder fixup! and squash! commits during interactive rebase.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-autosquash", "--apply"},
		},
		{
			Value:         "--no-autosquash",
			Description:   "Do not reorder fixup! and squash! commits.",
			Kind:          KindOption,
			ConflictsWith: []string{"--autosquash"},
		},
		{
			Value:         "--autostash",
			Description:   "Temporarily stash local changes before rebasing.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-autostash"},
		},
		{
			Value:         "--no-autostash",
			Description:   "Do not automatically stash local changes.",
			Kind:          KindOption,
			ConflictsWith: []string{"--autostash"},
		},
		{
			Value:         "--update-refs",
			Description:   "Update branches that point to rebased commits.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-update-refs", "--apply"},
		},
		{
			Value:         "--no-update-refs",
			Description:   "Do not update other branches pointing to rebased commits.",
			Kind:          KindOption,
			ConflictsWith: []string{"--update-refs"},
		},
		{
			Value:         "--rebase-merges",
			Description:   "Preserve merge commits while rebasing.",
			Kind:          KindOption,
			Aliases:       []string{"-r"},
			ConflictsWith: []string{"--apply"},
		},
		{
			Value:         "--root",
			Description:   "Rebase all reachable commits starting from the root.",
			Kind:          KindOption,
			ConflictsWith: []string{"--keep-base", "--apply"},
		},
		{
			Value:            "--empty",
			Description:      "Choose how commits that become empty are handled.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "mode",
			ValueDescription: "Enter drop, keep, or stop.",
			ConflictsWith:    []string{"--apply"},
		},
		{
			Value:       "--apply",
			Description: "Use the apply backend for the rebase.",
			Kind:        KindOption,
			ConflictsWith: []string{
				"--merge",
				"--strategy",
				"--strategy-option",
				"--autosquash",
				"--rebase-merges",
				"--interactive",
				"--exec",
				"--empty",
				"--update-refs",
				"--root",
			},
		},
		{
			Value:         "--merge",
			Description:   "Use merge strategies instead of applying patches.",
			Kind:          KindOption,
			Aliases:       []string{"-m"},
			ConflictsWith: []string{"--apply"},
		},
		{
			Value:            "--strategy",
			Description:      "Use the specified merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "strategy",
			ValueDescription: "Enter a merge strategy.",
			Aliases:          []string{"-s"},
			ConflictsWith:    []string{"--apply"},
		},
		{
			Value:            "--strategy-option",
			Description:      "Pass an option to the selected merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "option",
			ValueDescription: "Enter a merge strategy option.",
			Repeatable:       true,
			Aliases:          []string{"-X"},
			ConflictsWith:    []string{"--apply"},
		},
		{
			Value:       "--force-rebase",
			Description: "Replay every commit even when it appears unchanged.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "--signoff",
			Description: "Add a Signed-off-by trailer to each rebased commit.",
			Kind:        KindOption,
		},
		{
			Value:       "--no-verify",
			Description: "Bypass the pre-rebase hook.",
			Kind:        KindOption,
		},
		{
			Value:         "--continue",
			Description:   "Continue after resolving conflicts.",
			Kind:          KindOption,
			ConflictsWith: []string{"--skip", "--abort", "--quit", "--edit-todo", "--show-current-patch"},
		},
		{
			Value:         "--skip",
			Description:   "Skip the current commit and continue.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--abort", "--quit", "--edit-todo", "--show-current-patch"},
		},
		{
			Value:         "--abort",
			Description:   "Cancel the rebase and restore the original branch.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--quit", "--edit-todo", "--show-current-patch"},
		},
		{
			Value:         "--quit",
			Description:   "Stop rebasing without restoring the original branch.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--abort", "--edit-todo", "--show-current-patch"},
		},
		{
			Value:         "--edit-todo",
			Description:   "Edit the todo list of an interactive rebase.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--abort", "--quit", "--show-current-patch"},
		},
		{
			Value:         "--show-current-patch",
			Description:   "Show the patch currently being applied.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--abort", "--quit", "--edit-todo"},
		},
	},
	"bisect start": {
		{
			Value:            "--term-bad",
			Description:      "Choose a custom term for commits containing the new state.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "term",
			ValueDescription: "Enter the term representing the newer state.",
			ConflictsWith:    []string{"--term-new"},
		},
		{
			Value:            "--term-new",
			Description:      "Choose a custom term for commits containing the new state.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "term",
			ValueDescription: "Enter the term representing the newer state.",
			ConflictsWith:    []string{"--term-bad"},
		},
		{
			Value:            "--term-good",
			Description:      "Choose a custom term for commits containing the old state.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "term",
			ValueDescription: "Enter the term representing the older state.",
			ConflictsWith:    []string{"--term-old"},
		},
		{
			Value:            "--term-old",
			Description:      "Choose a custom term for commits containing the old state.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "term",
			ValueDescription: "Enter the term representing the older state.",
			ConflictsWith:    []string{"--term-good"},
		},
		{
			Value:       "--no-checkout",
			Description: "Update BISECT_HEAD without checking out each tested commit.",
			Kind:        KindOption,
		},
		{
			Value:       "--first-parent",
			Description: "Follow only first parents when traversing merge commits.",
			Kind:        KindOption,
		},
	},
	"bisect terms": {
		{
			Value:         "--term-good",
			Description:   "Print the term representing the older state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--term-old", "--term-bad", "--term-new"},
		},
		{
			Value:         "--term-old",
			Description:   "Print the term representing the older state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--term-good", "--term-bad", "--term-new"},
		},
		{
			Value:         "--term-bad",
			Description:   "Print the term representing the newer state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--term-good", "--term-old", "--term-new"},
		},
		{
			Value:         "--term-new",
			Description:   "Print the term representing the newer state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--term-good", "--term-old", "--term-bad"},
		},
	},
	"worktree add": {
		{
			Value:       "--force",
			Description: "Create the worktree even when the branch is already checked out.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "--detach",
			Description: "Create the worktree with a detached HEAD.",
			Kind:        KindOption,
		},
		{
			Value:         "--checkout",
			Description:   "Check out files in the new working tree.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-checkout"},
		},
		{
			Value:         "--no-checkout",
			Description:   "Create the worktree without checking out files.",
			Kind:          KindOption,
			ConflictsWith: []string{"--checkout"},
		},
		{
			Value:       "--lock",
			Description: "Lock the new worktree after creating it.",
			Kind:        KindOption,
		},
		{
			Value:            "--reason",
			Description:      "Record a reason for locking the worktree.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "reason",
			ValueDescription: "Enter a reason for the worktree lock.",
		},
		{
			Value:       "--orphan",
			Description: "Create the worktree using a new unborn branch.",
			Kind:        KindOption,
		},
		{
			Value:            "-b",
			Description:      "Create a new branch for the worktree.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter the name of the new branch.",
			ConflictsWith:    []string{"-B"},
		},
		{
			Value:            "-B",
			Description:      "Create or reset a branch for the worktree.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter the name of the branch to create or reset.",
			ConflictsWith:    []string{"-b"},
		},
	},
	"worktree list": {
		{
			Value:         "--verbose",
			Description:   "Show additional information about each worktree.",
			Kind:          KindOption,
			Aliases:       []string{"-v"},
			ConflictsWith: []string{"--porcelain"},
		},
		{
			Value:         "--porcelain",
			Description:   "Use a stable machine-readable output format.",
			Kind:          KindOption,
			ConflictsWith: []string{"--verbose"},
		},
		{
			Value:       "-z",
			Description: "Terminate fields with NUL characters in porcelain output.",
			Kind:        KindOption,
		},
	},
	"worktree lock": {
		{
			Value:            "--reason",
			Description:      "Record why the worktree is locked.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "reason",
			ValueDescription: "Enter a reason for locking the worktree.",
		},
	},
	"worktree prune": {
		{
			Value:       "--dry-run",
			Description: "Show stale metadata without removing it.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--verbose",
			Description: "Report each stale worktree entry that is removed.",
			Kind:        KindOption,
			Aliases:     []string{"-v"},
		},
		{
			Value:            "--expire",
			Description:      "Only prune worktree metadata older than the specified time.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "time",
			ValueDescription: "Enter an expiry time such as now or 2.weeks.ago.",
		},
	},
	"worktree remove": {
		{
			Value:       "--force",
			Description: "Remove a worktree even when it contains changes.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
	},
	"submodule": {
		{
			Value:       "--quiet",
			Description: "Only print error messages.",
			Kind:        KindOption,
			Aliases:     []string{"-q"},
		},
		{
			Value:       "--cached",
			Description: "Show the submodule commits recorded in the index.",
			Kind:        KindOption,
		},
	},
	"submodule add": {
		{
			Value:            "--branch",
			Description:      "Record a branch for future remote updates.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter the branch tracked by the submodule.",
			Aliases:          []string{"-b"},
		},
		{
			Value:       "--force",
			Description: "Allow an ignored path or reuse an existing submodule name.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:            "--name",
			Description:      "Use a custom logical name for the submodule.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "name",
			ValueDescription: "Enter the logical submodule name.",
		},
		{
			Value:            "--reference",
			Description:      "Use a local repository as an object reference.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "repository",
			ValueDescription: "Enter the path of the reference repository.",
		},
		{
			Value:            "--ref-format",
			Description:      "Select the reference storage format.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "format",
			ValueDescription: "Enter the reference storage format.",
		},
		{
			Value:            "--depth",
			Description:      "Create a shallow clone with limited history.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "depth",
			ValueDescription: "Enter the number of revisions to clone.",
		},
		{
			Value:       "--progress",
			Description: "Force progress output.",
			Kind:        KindOption,
		},
		{
			Value:       "--dissociate",
			Description: "Stop depending on the reference repository after cloning.",
			Kind:        KindOption,
		},
	},
	"submodule status": {
		{
			Value:       "--cached",
			Description: "Show commits recorded in the index.",
			Kind:        KindOption,
		},
		{
			Value:       "--recursive",
			Description: "Show the status of nested submodules recursively.",
			Kind:        KindOption,
		},
	},
	"submodule deinit": {
		{
			Value:       "--force",
			Description: "Remove submodule working trees containing local changes.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "--all",
			Description: "Unregister every submodule in the working tree.",
			Kind:        KindOption,
		},
	},
	"submodule update": {
		{
			Value:       "--init",
			Description: "Initialize unregistered submodules before updating.",
			Kind:        KindOption,
		},
		{
			Value:       "--remote",
			Description: "Update from the remote-tracking branch.",
			Kind:        KindOption,
		},
		{
			Value:       "--no-fetch",
			Description: "Do not fetch new objects from the remote.",
			Kind:        KindOption,
			Aliases:     []string{"-N"},
		},
		{
			Value:       "--force",
			Description: "Force checkout even when local changes would be discarded.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:         "--checkout",
			Description:   "Check out the recorded commit in detached HEAD state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--merge", "--rebase"},
		},
		{
			Value:         "--merge",
			Description:   "Merge the recorded commit into the current branch.",
			Kind:          KindOption,
			ConflictsWith: []string{"--checkout", "--rebase"},
		},
		{
			Value:         "--rebase",
			Description:   "Rebase the current branch onto the recorded commit.",
			Kind:          KindOption,
			ConflictsWith: []string{"--checkout", "--merge"},
		},
		{
			Value:            "--reference",
			Description:      "Use a local repository as an object reference.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "repository",
			ValueDescription: "Enter the path of the reference repository.",
		},
		{
			Value:            "--ref-format",
			Description:      "Select the reference storage format for new clones.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "format",
			ValueDescription: "Enter the reference storage format.",
		},
		{
			Value:            "--depth",
			Description:      "Create shallow submodule clones.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "depth",
			ValueDescription: "Enter the number of revisions to clone.",
		},
		{
			Value:       "--recursive",
			Description: "Update nested submodules recursively.",
			Kind:        KindOption,
		},
		{
			Value:            "--jobs",
			Description:      "Clone multiple submodules in parallel.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "count",
			ValueDescription: "Enter the maximum number of parallel jobs.",
			Aliases:          []string{"-j"},
		},
		{
			Value:         "--recommend-shallow",
			Description:   "Use shallow-clone recommendations from .gitmodules.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-recommend-shallow"},
		},
		{
			Value:         "--no-recommend-shallow",
			Description:   "Ignore shallow-clone recommendations from .gitmodules.",
			Kind:          KindOption,
			ConflictsWith: []string{"--recommend-shallow"},
		},
		{
			Value:         "--single-branch",
			Description:   "Clone only the selected branch.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-single-branch"},
		},
		{
			Value:         "--no-single-branch",
			Description:   "Allow cloning more than one branch.",
			Kind:          KindOption,
			ConflictsWith: []string{"--single-branch"},
		},
		{
			Value:            "--filter",
			Description:      "Apply a partial-clone object filter.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "filter",
			ValueDescription: "Enter a partial-clone filter specification.",
		},
		{
			Value:       "--progress",
			Description: "Force progress output.",
			Kind:        KindOption,
		},
		{
			Value:       "--dissociate",
			Description: "Stop depending on the reference repository after cloning.",
			Kind:        KindOption,
		},
	},
	"submodule set-branch": {
		{
			Value:            "--branch",
			Description:      "Set the branch tracked by the submodule.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter the remote branch to track.",
			Aliases:          []string{"-b"},
			ConflictsWith:    []string{"--default", "-d"},
		},
		{
			Value:         "--default",
			Description:   "Return to tracking the remote default branch.",
			Kind:          KindOption,
			Aliases:       []string{"-d"},
			ConflictsWith: []string{"--branch", "-b"},
		},
	},
	"submodule summary": {
		{
			Value:         "--cached",
			Description:   "Compare the specified commit with the index.",
			Kind:          KindOption,
			ConflictsWith: []string{"--files"},
		},
		{
			Value:         "--files",
			Description:   "Compare the index with the submodule working tree.",
			Kind:          KindOption,
			ConflictsWith: []string{"--cached"},
		},
		{
			Value:            "--summary-limit",
			Description:      "Limit the number of commits shown.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "count",
			ValueDescription: "Enter the maximum number of commits to show.",
			Aliases:          []string{"-n"},
		},
	},
	"submodule foreach": {
		{
			Value:       "--recursive",
			Description: "Run the command in nested submodules recursively.",
			Kind:        KindOption,
		},
	},
	"submodule sync": {
		{
			Value:       "--recursive",
			Description: "Synchronize URLs in nested submodules recursively.",
			Kind:        KindOption,
		},
	},
	"show": {
		{
			Value:       "--patch",
			Description: "Show the patch introduced by the object.",
			Kind:        KindOption,
			Aliases:     []string{"-p"},
			ConflictsWith: []string{
				"--no-patch", "--quiet", "-q",
			},
		},
		{
			Value:       "--no-patch",
			Description: "Do not show patch output.",
			Kind:        KindOption,
			Aliases:     []string{"-s"},
			ConflictsWith: []string{
				"--patch", "-p",
			},
		},
		{
			Value:       "--quiet",
			Description: "Suppress diff output.",
			Kind:        KindOption,
			Aliases:     []string{"-q"},
			ConflictsWith: []string{
				"--patch", "-p",
			},
		},
		{
			Value:       "--stat",
			Description: "Show a summary of changed files.",
			Kind:        KindOption,
		},
		{
			Value:       "--name-only",
			Description: "Show only the names of changed files.",
			Kind:        KindOption,
			ConflictsWith: []string{
				"--name-status",
			},
		},
		{
			Value:       "--name-status",
			Description: "Show changed file names and their status.",
			Kind:        KindOption,
			ConflictsWith: []string{
				"--name-only",
			},
		},
		{
			Value:            "--format",
			Description:      "Select the commit display format.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "format",
			ValueDescription: "Enter a pretty-print format such as oneline or full.",
		},
		{
			Value:       "--pretty",
			Description: "Pretty-print commit information.",
			Kind:        KindOption,
		},
		{
			Value:       "--oneline",
			Description: "Show each commit on a single line.",
			Kind:        KindOption,
		},
		{
			Value:         "--abbrev-commit",
			Description:   "Show abbreviated commit object names.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-abbrev-commit"},
		},
		{
			Value:         "--no-abbrev-commit",
			Description:   "Show full commit object names.",
			Kind:          KindOption,
			ConflictsWith: []string{"--abbrev-commit"},
		},
		{
			Value:       "--show-signature",
			Description: "Verify and display a signed commit signature.",
			Kind:        KindOption,
		},
		{
			Value:       "--decorate",
			Description: "Show reference names pointing to commits.",
			Kind:        KindOption,
		},
	},
	"blame": {
		{
			Value:       "--incremental",
			Description: "Show blame entries incrementally as they are found.",
			Kind:        KindOption,
			ConflictsWith: []string{
				"--porcelain", "--line-porcelain",
			},
		},
		{
			Value:       "--porcelain",
			Description: "Use a machine-readable output format.",
			Kind:        KindOption,
			Aliases:     []string{"-p"},
			ConflictsWith: []string{
				"--incremental", "--line-porcelain",
			},
		},
		{
			Value:       "--line-porcelain",
			Description: "Show full commit information for every source line.",
			Kind:        KindOption,
			ConflictsWith: []string{
				"--incremental", "--porcelain", "-p",
			},
		},
		{
			Value:       "--root",
			Description: "Do not treat root commits as boundaries.",
			Kind:        KindOption,
		},
		{
			Value:       "--show-stats",
			Description: "Show statistics about the blame calculation.",
			Kind:        KindOption,
		},
		{
			Value:       "--show-name",
			Description: "Show the original filename.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "--show-number",
			Description: "Show the original line number.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--show-email",
			Description: "Show author email addresses instead of names.",
			Kind:        KindOption,
			Aliases:     []string{"-e"},
		},
		{
			Value:       "--ignore-whitespace",
			Description: "Ignore whitespace when comparing parent versions.",
			Kind:        KindOption,
			Aliases:     []string{"-w"},
		},
		{
			Value:            "--ignore-rev",
			Description:      "Ignore changes introduced by a revision.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "revision",
			ValueDescription: "Enter a revision to ignore.",
			Repeatable:       true,
		},
		{
			Value:            "--ignore-revs-file",
			Description:      "Read revisions to ignore from a file.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "file",
			ValueDescription: "Enter the file containing revisions to ignore.",
			Repeatable:       true,
		},
		{
			Value:            "--contents",
			Description:      "Use another file as the final version being blamed.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "file",
			ValueDescription: "Enter the file whose contents should be blamed.",
		},
		{
			Value:            "-L",
			Description:      "Restrict blame output to a line or function range.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "range",
			ValueDescription: "Enter a line range such as 20,40 or :function.",
			Repeatable:       true,
		},
		{
			Value:            "--abbrev",
			Description:      "Control displayed object-name length.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "length",
			ValueDescription: "Enter the number of hexadecimal digits.",
		},
		{
			Value:       "--color-lines",
			Description: "Color repeated metadata from adjacent lines.",
			Kind:        KindOption,
		},
		{
			Value:       "--color-by-age",
			Description: "Color source lines according to their age.",
			Kind:        KindOption,
		},
		{
			Value:       "--minimal",
			Description: "Spend additional time finding a smaller blame result.",
			Kind:        KindOption,
		},
		{
			Value:       "-M",
			Description: "Detect moved lines within a file.",
			Kind:        KindOption,
		},
		{
			Value:       "-C",
			Description: "Detect copied or moved lines across files.",
			Kind:        KindOption,
			Repeatable:  true,
		},
	},
	"grep": {
		{
			Value:       "--cached",
			Description: "Search blobs recorded in the index.",
			Kind:        KindOption,
			ConflictsWith: []string{
				"--no-index",
			},
		},
		{
			Value:       "--no-index",
			Description: "Search files outside Git control.",
			Kind:        KindOption,
			ConflictsWith: []string{
				"--cached", "--untracked",
			},
		},
		{
			Value:       "--untracked",
			Description: "Search tracked and untracked files.",
			Kind:        KindOption,
			ConflictsWith: []string{
				"--no-index",
			},
		},
		{
			Value:       "--recurse-submodules",
			Description: "Search recursively inside active submodules.",
			Kind:        KindOption,
		},
		{
			Value:       "--invert-match",
			Description: "Select lines that do not match.",
			Kind:        KindOption,
			Aliases:     []string{"-v"},
		},
		{
			Value:       "--ignore-case",
			Description: "Match patterns without regard to case.",
			Kind:        KindOption,
			Aliases:     []string{"-i"},
		},
		{
			Value:       "--word-regexp",
			Description: "Match patterns only at word boundaries.",
			Kind:        KindOption,
			Aliases:     []string{"-w"},
		},
		{
			Value:       "--text",
			Description: "Process binary files as text.",
			Kind:        KindOption,
			Aliases:     []string{"-a"},
		},
		{
			Value:         "--extended-regexp",
			Description:   "Use extended POSIX regular expressions.",
			Kind:          KindOption,
			Aliases:       []string{"-E"},
			ConflictsWith: []string{"--basic-regexp", "--fixed-strings", "--perl-regexp"},
		},
		{
			Value:         "--basic-regexp",
			Description:   "Use basic POSIX regular expressions.",
			Kind:          KindOption,
			Aliases:       []string{"-G"},
			ConflictsWith: []string{"--extended-regexp", "--fixed-strings", "--perl-regexp"},
		},
		{
			Value:         "--fixed-strings",
			Description:   "Interpret the pattern as a fixed string.",
			Kind:          KindOption,
			Aliases:       []string{"-F"},
			ConflictsWith: []string{"--extended-regexp", "--basic-regexp", "--perl-regexp"},
		},
		{
			Value:         "--perl-regexp",
			Description:   "Use Perl-compatible regular expressions.",
			Kind:          KindOption,
			Aliases:       []string{"-P"},
			ConflictsWith: []string{"--extended-regexp", "--basic-regexp", "--fixed-strings"},
		},
		{
			Value:       "--line-number",
			Description: "Show line numbers for matches.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--column",
			Description: "Show the column number of the first match.",
			Kind:        KindOption,
		},
		{
			Value:       "--files-with-matches",
			Description: "Show only names of files containing matches.",
			Kind:        KindOption,
			Aliases:     []string{"-l", "--name-only"},
		},
		{
			Value:       "--files-without-match",
			Description: "Show only names of files without matches.",
			Kind:        KindOption,
			Aliases:     []string{"-L"},
		},
		{
			Value:       "--only-matching",
			Description: "Show only matching portions of each line.",
			Kind:        KindOption,
			Aliases:     []string{"-o"},
		},
		{
			Value:       "--count",
			Description: "Show the number of matches in each file.",
			Kind:        KindOption,
			Aliases:     []string{"-c"},
		},
		{
			Value:       "--break",
			Description: "Print an empty line between matches from different files.",
			Kind:        KindOption,
		},
		{
			Value:       "--heading",
			Description: "Show each filename once above its matching lines.",
			Kind:        KindOption,
		},
		{
			Value:            "--context",
			Description:      "Show lines before and after each match.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "lines",
			ValueDescription: "Enter the number of surrounding lines.",
			Aliases:          []string{"-C"},
		},
		{
			Value:            "--before-context",
			Description:      "Show lines before each match.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "lines",
			ValueDescription: "Enter the number of preceding lines.",
			Aliases:          []string{"-B"},
		},
		{
			Value:            "--after-context",
			Description:      "Show lines after each match.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "lines",
			ValueDescription: "Enter the number of following lines.",
			Aliases:          []string{"-A"},
		},
		{
			Value:            "--max-depth",
			Description:      "Limit directory recursion depth.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "depth",
			ValueDescription: "Enter the maximum directory depth.",
		},
		{
			Value:            "--max-count",
			Description:      "Limit matches reported per file.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "count",
			ValueDescription: "Enter the maximum matches per file.",
			Aliases:          []string{"-m"},
		},
		{
			Value:            "-e",
			Description:      "Add a pattern to match.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "pattern",
			ValueDescription: "Enter a search pattern.",
			Repeatable:       true,
		},
		{
			Value:            "-f",
			Description:      "Read search patterns from a file.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "file",
			ValueDescription: "Enter a file containing search patterns.",
			Repeatable:       true,
		},
		{
			Value:       "--and",
			Description: "Require both adjacent pattern expressions.",
			Kind:        KindOption,
			Repeatable:  true,
		},
		{
			Value:       "--or",
			Description: "Allow either adjacent pattern expression.",
			Kind:        KindOption,
			Repeatable:  true,
		},
		{
			Value:       "--not",
			Description: "Negate the following pattern expression.",
			Kind:        KindOption,
			Repeatable:  true,
		},
		{
			Value:       "--quiet",
			Description: "Return status without printing matches.",
			Kind:        KindOption,
			Aliases:     []string{"-q"},
		},
	},
	"shortlog": {
		{
			Value:       "--committer",
			Description: "Group commits by committer instead of author.",
			Kind:        KindOption,
			Aliases:     []string{"-c"},
		},
		{
			Value:       "--numbered",
			Description: "Sort authors by number of commits.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--summary",
			Description: "Show only commit counts.",
			Kind:        KindOption,
			Aliases:     []string{"-s"},
		},
		{
			Value:       "--email",
			Description: "Show each author's email address.",
			Kind:        KindOption,
			Aliases:     []string{"-e"},
		},
		{
			Value:            "--group",
			Description:      "Select the field used to group commits.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "field",
			ValueDescription: "Enter a grouping field such as author or committer.",
		},
	},
	"describe": {
		{
			Value:       "--all",
			Description: "Use any reference instead of annotated tags only.",
			Kind:        KindOption,
		},
		{
			Value:       "--tags",
			Description: "Include lightweight tags.",
			Kind:        KindOption,
		},
		{
			Value:       "--contains",
			Description: "Find a tag containing the specified commit.",
			Kind:        KindOption,
		},
		{
			Value:            "--abbrev",
			Description:      "Control abbreviated object-name length.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "length",
			ValueDescription: "Enter the number of hexadecimal digits.",
		},
		{
			Value:            "--candidates",
			Description:      "Limit the number of candidate tags considered.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "count",
			ValueDescription: "Enter the maximum number of candidate tags.",
		},
		{
			Value:       "--exact-match",
			Description: "Only output a tag that directly references the object.",
			Kind:        KindOption,
		},
		{
			Value:       "--debug",
			Description: "Show details about the search strategy.",
			Kind:        KindOption,
		},
		{
			Value:       "--long",
			Description: "Always use the long description format.",
			Kind:        KindOption,
		},
		{
			Value:            "--match",
			Description:      "Consider only tags matching a pattern.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "pattern",
			ValueDescription: "Enter a tag glob pattern.",
			Repeatable:       true,
		},
		{
			Value:            "--exclude",
			Description:      "Exclude tags matching a pattern.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "pattern",
			ValueDescription: "Enter a tag glob pattern to exclude.",
			Repeatable:       true,
		},
		{
			Value:       "--always",
			Description: "Fall back to an abbreviated commit object name.",
			Kind:        KindOption,
		},
		{
			Value:       "--dirty",
			Description: "Append a suffix when the working tree is modified.",
			Kind:        KindOption,
		},
		{
			Value:       "--broken",
			Description: "Append a suffix when repository state cannot be checked.",
			Kind:        KindOption,
		},
		{
			Value:       "--first-parent",
			Description: "Follow only first parents through merge commits.",
			Kind:        KindOption,
		},
	},
	"reflog": {
		{
			Value:            "--date",
			Description:      "Select how reflog dates are displayed.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "format",
			ValueDescription: "Enter a date format such as relative or iso.",
		},
		{
			Value:       "--oneline",
			Description: "Show each reflog entry on one line.",
			Kind:        KindOption,
		},
		{
			Value:       "--all",
			Description: "Show reflogs from all references.",
			Kind:        KindOption,
		},
	},
	"reflog show": {
		{
			Value:            "--date",
			Description:      "Select how reflog dates are displayed.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "format",
			ValueDescription: "Enter a date format such as relative or iso.",
		},
		{
			Value:            "--format",
			Description:      "Select the reflog entry display format.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "format",
			ValueDescription: "Enter a pretty-print format.",
		},
		{
			Value:       "--pretty",
			Description: "Pretty-print reflog entries.",
			Kind:        KindOption,
		},
		{
			Value:       "--oneline",
			Description: "Show each reflog entry on one line.",
			Kind:        KindOption,
		},
		{
			Value:       "--all",
			Description: "Show reflogs from all references.",
			Kind:        KindOption,
		},
	},
	"reflog delete": {
		{
			Value:       "--rewrite",
			Description: "Rewrite the old object ID of following entries.",
			Kind:        KindOption,
		},
		{
			Value:       "--updateref",
			Description: "Update the reference when its top entry is removed.",
			Kind:        KindOption,
		},
		{
			Value:       "--dry-run",
			Description: "Show entries that would be removed.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--verbose",
			Description: "Report each reflog entry that is removed.",
			Kind:        KindOption,
		},
	},
	"reflog drop": {
		{
			Value:       "--all",
			Description: "Drop reflogs for all references.",
			Kind:        KindOption,
		},
		{
			Value:       "--single-worktree",
			Description: "Limit --all to the current worktree.",
			Kind:        KindOption,
		},
	},
	"reflog expire": {
		{
			Value:            "--expire",
			Description:      "Remove entries older than a specified time.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "time",
			ValueDescription: "Enter an expiry time such as 30.days.ago.",
		},
		{
			Value:            "--expire-unreachable",
			Description:      "Remove unreachable entries older than a specified time.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "time",
			ValueDescription: "Enter an expiry time for unreachable entries.",
		},
		{
			Value:       "--rewrite",
			Description: "Rewrite preceding object IDs after pruning entries.",
			Kind:        KindOption,
		},
		{
			Value:       "--updateref",
			Description: "Update references after pruning their top entries.",
			Kind:        KindOption,
		},
		{
			Value:       "--stale-fix",
			Description: "Remove entries referring to broken commits.",
			Kind:        KindOption,
		},
		{
			Value:       "--dry-run",
			Description: "Show entries that would be pruned.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--verbose",
			Description: "Report each reflog entry that is pruned.",
			Kind:        KindOption,
		},
		{
			Value:       "--all",
			Description: "Process reflogs for all references.",
			Kind:        KindOption,
		},
		{
			Value:       "--single-worktree",
			Description: "Limit --all to the current worktree.",
			Kind:        KindOption,
		},
	},
}
