package suggest

var gitSubcommands = []Suggestion{
	{
		Value:       "status",
		Description: "Show the working tree status.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "add",
		Description: "Add file changes to the staging area.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "commit",
		Description: "Record staged changes in repository history.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "branch",
		Description: "List, create, or delete branches.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "switch",
		Description: "Switch branches or create a new branch.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "checkout",
		Description: "Switch branches or restore working tree files.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "restore",
		Description: "Restore working tree files.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "log",
		Description: "Show commit history.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "diff",
		Description: "Show changes between commits and working trees.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "merge",
		Description: "Join development histories together.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "rebase",
		Description: "Reapply commits on top of another base.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "fetch",
		Description: "Download objects and refs from a remote.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "pull",
		Description: "Fetch and integrate changes from a remote.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "push",
		Description: "Update remote refs and transfer objects.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "stash",
		Description: "Temporarily store uncommitted changes.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "clone",
		Description: "Clone a repository into a new directory.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "init",
		Description: "Create an empty Git repository.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "remote",
		Description: "Manage tracked remote repositories.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "tag",
		Description: "Create, list, delete, or verify tags.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "reset",
		Description: "Reset the current HEAD to a specified state.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "revert",
		Description: "Create commits that reverse earlier commits.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "cherry-pick",
		Description: "Apply changes introduced by existing commits.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "clean",
		Description: "Remove untracked files from the working tree.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "rm",
		Description: "Remove files from the working tree and index.",
		Kind:        KindSubcommand,
	},
	{
		Value:       "mv",
		Description: "Move or rename files, directories, or symbolic links.",
		Kind:        KindSubcommand,
	},
}

var gitNestedSubcommands = map[string][]Suggestion{
	"remote": {
		{
			Value:       "add",
			Description: "Add a new remote repository.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "rename",
			Description: "Rename an existing remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "remove",
			Description: "Remove an existing remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "set-head",
			Description: "Set or delete the default branch for a remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "set-branches",
			Description: "Change the branches tracked for a remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "get-url",
			Description: "Show the URL of a remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "set-url",
			Description: "Change the URL of a remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "show",
			Description: "Show information about a remote.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "prune",
			Description: "Delete stale remote-tracking references.",
			Kind:        KindSubcommand,
		},
		{
			Value:       "update",
			Description: "Fetch updates for one or more remotes.",
			Kind:        KindSubcommand,
		},
	},
}

var gitOptions = map[string][]Suggestion{
	"branch": {
		{
			Value:       "--show-current",
			Description: "Print the name of the current branch.",
			Kind:        KindOption,
		},
		{
			Value:       "--merged",
			Description: "List branches already merged into the specified commit.",
			Kind:        KindOption,
		},
		{
			Value:       "--no-merged",
			Description: "List branches that have not been merged.",
			Kind:        KindOption,
		},
		{
			Value:       "--delete",
			Description: "Delete a branch.",
			Kind:        KindOption,
		},
	},
	"status": {
		{
			Value:       "--short",
			Description: "Show status in a compact format.",
			Kind:        KindOption,
		},
		{
			Value:       "--branch",
			Description: "Show branch information.",
			Kind:        KindOption,
		},
		{
			Value:       "--porcelain",
			Description: "Use a stable machine-readable format.",
			Kind:        KindOption,
		},
	},
	"add": {
		{
			Value:       "--all",
			Description: "Stage changes from the entire working tree.",
			Kind:        KindOption,
		},
		{
			Value:       "--patch",
			Description: "Interactively choose changes to stage.",
			Kind:        KindOption,
		},
		{
			Value:       "--update",
			Description: "Stage modified and deleted tracked files.",
			Kind:        KindOption,
		},
	},
	"commit": {
		{
			Value:            "--message",
			Description:      "Use the supplied text as the commit message; repeat it to add paragraphs.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "message",
			ValueDescription: "Enter the commit message. Quotes are recommended.",
			Repeatable:       true,
			Aliases:          []string{"-m"},
		},
		{
			Value:       "--amend",
			Description: "Replace the most recent commit.",
			Kind:        KindOption,
		},
		{
			Value:       "--all",
			Description: "Stage modified and deleted tracked files before committing.",
			Kind:        KindOption,
		},
		{
			Value:       "--no-verify",
			Description: "Skip commit hooks.",
			Kind:        KindOption,
		},
	},
	"switch": {
		{
			Value:       "--create",
			Description: "Create a new branch and switch to it.",
			Kind:        KindOption,
		},
		{
			Value:       "--detach",
			Description: "Switch to a commit without attaching HEAD to a branch.",
			Kind:        KindOption,
		},
	},
	"log": {
		{
			Value:       "--oneline",
			Description: "Show each commit on one line.",
			Kind:        KindOption,
		},
		{
			Value:       "--graph",
			Description: "Draw a text-based commit graph.",
			Kind:        KindOption,
		},
		{
			Value:       "--all",
			Description: "Show commits from all refs.",
			Kind:        KindOption,
		},
	},
	"clone": {
		{
			Value:            "--branch",
			Description:      "Check out the specified branch after cloning.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter the branch or tag to check out.",
			Aliases:          []string{"-b"},
		},
		{
			Value:            "--depth",
			Description:      "Create a shallow clone with limited history.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "depth",
			ValueDescription: "Enter the number of commits to include",
		},
		{
			Value:            "--origin",
			Description:      "Use a remote name other than origin.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "name",
			ValueDescription: "Enter the name of the remote.",
			Aliases:          []string{"-o"},
		},
		{
			Value:       "--single-branch",
			Description: "Clone only the history of one branch.",
			Kind:        KindOption,
		},
		{
			Value:       "--recurse-submodules",
			Description: "Initialize and clone submodules.",
			Kind:        KindOption,
		},
		{
			Value:       "--no-checkout",
			Description: "Do not checkout HEAD after cloning.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--bare",
			Description: "Create a bare repository.",
			Kind:        KindOption,
		},
		{
			Value:       "--mirror",
			Description: "Create a mirror of the source repository.",
			Kind:        KindOption,
		},
	},
	"init": {
		{
			Value:       "--bare",
			Description: "Create a bare repository.",
			Kind:        KindOption,
		},
		{
			Value:            "--initial-branch",
			Description:      "Use the specified name for the initial branch.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter the name of the initial branch.",
			Aliases:          []string{"-b"},
		},
		{
			Value:            "--template",
			Description:      "Use templates from the specified directory.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "directory",
			ValueDescription: "Enter the template directory.",
		},
		{
			Value:            "--separate-git-dir",
			Description:      "Store repository metadata in a separate directory.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "git-dir",
			ValueDescription: "Enter the Git metadata directory.",
		},
	},
	"remote": {
		{
			Value:       "--verbose",
			Description: "Show remote URLs in addition to remote names",
			Kind:        KindOption,
			Aliases:     []string{"-v"},
		},
	},
	"remote add": {
		{
			Value:       "-f",
			Description: "Fetch the remote immediately after adding it.",
			Kind:        KindOption,
		},
		{
			Value:            "-t",
			Description:      "Track only the specified branch; repeat it to track multiple branches.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter a remote branch to track.",
			Repeatable:       true,
		},
		{
			Value:            "-m",
			Description:      "Set the remote's default branch.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "branch",
			ValueDescription: "Enter the remote's default branch.",
		},
		{
			Value:         "--tags",
			Description:   "Import every tag from the remote.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-tags"},
		},
		{
			Value:         "--no-tags",
			Description:   "Do not import tags from the remote.",
			Kind:          KindOption,
			ConflictsWith: []string{"--tags"},
		},
		{
			Value:       "--mirror=",
			Description: "Create a fetch or push mirror; append fetch or push.",
			Kind:        KindOption,
		},
	},
	"remote rename": {
		{
			Value:         "--progress",
			Description:   "Show progress while renaming remote references.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-progress"},
		},
		{
			Value:         "--no-progress",
			Description:   "Do not show progress while renaming remote references.",
			Kind:          KindOption,
			ConflictsWith: []string{"--progress"},
		},
	},
	"remote set-head": {
		{
			Value:         "--auto",
			Description:   "Query the remote and set its default branch automatically.",
			Kind:          KindOption,
			Aliases:       []string{"-a"},
			ConflictsWith: []string{"--delete"},
		},
		{
			Value:         "--delete",
			Description:   "Delete the remote's default-branch reference.",
			Kind:          KindOption,
			Aliases:       []string{"-d"},
			ConflictsWith: []string{"--auto"},
		},
	},
	"remote set-branches": {
		{
			Value:       "--add",
			Description: "Add branches instead of replacing the tracked branch list.",
			Kind:        KindOption,
		},
	},
	"remote get-url": {
		{
			Value:       "--push",
			Description: "Show push URLs instead of fetch URLs.",
			Kind:        KindOption,
		},
		{
			Value:       "--all",
			Description: "Show all URLs for the remote.",
			Kind:        KindOption,
		},
	},
	"remote set-url": {
		{
			Value:       "--push",
			Description: "Change push URLs instead of fetch URLs.",
			Kind:        KindOption,
		},
		{
			Value:         "--add",
			Description:   "Add a new URL instead of replacing an existing URL.",
			Kind:          KindOption,
			ConflictsWith: []string{"--delete"},
		},
		{
			Value:         "--delete",
			Description:   "Delete URLs matching the supplied regular expression.",
			Kind:          KindOption,
			ConflictsWith: []string{"--add"},
		},
	},
	"remote show": {
		{
			Value:       "--no-query",
			Description: "Use cached information without querying the remote.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
	},
	"remote prune": {
		{
			Value:       "--dry-run",
			Description: "Report stale references without deleting them.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
	},
	"remote update": {
		{
			Value:       "--prune",
			Description: "Prune stale references while updating remotes.",
			Kind:        KindOption,
			Aliases:     []string{"-p"},
		},
	},
	"tag": {
		{
			Value:       "--list",
			Description: "List tags, optionally matching a pattern",
			Kind:        KindOption,
			Aliases:     []string{"-l"},
		},
		{
			Value:       "--annotate",
			Description: "Create an annotated tag.",
			Kind:        KindOption,
			Aliases:     []string{"-a"},
		},
		{
			Value:            "--message",
			Description:      "Use the supplied annotation message.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "message",
			ValueDescription: "Enter the tag annotation message.",
			Repeatable:       true,
			Aliases:          []string{"-m"},
		},
		{
			Value:       "--delete",
			Description: "Delete one or more tags.",
			Kind:        KindOption,
			Aliases:     []string{"-d"},
		},
		{
			Value:       "--force",
			Description: "Replace an existing tag.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "--sign",
			Description: "Create a GPG-signed tag",
			Kind:        KindOption,
			Aliases:     []string{"-s"},
		},
		{
			Value:       "--verify",
			Description: "Verify the GPG signature of a tag",
			Kind:        KindOption,
			Aliases:     []string{"-v"},
		},
		{
			Value:            "--contains",
			Description:      "List tags containing the specified commit.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "commit",
			ValueDescription: "Enter a commit or revision",
		},
		{
			Value:            "--points-at",
			Description:      "List tags pointing at the specified object.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "object",
			ValueDescription: "Enter a Git object name.",
		},
	},
	"reset": {
		{
			Value:         "--soft",
			Description:   "Reset HEAD only; keep the index and working tree unchanged.",
			Kind:          KindOption,
			ConflictsWith: []string{"--mixed", "--hard", "--merge", "--keep", "--patch"},
		},
		{
			Value:         "--mixed",
			Description:   "Reset HEAD and the index, but keep working tree changes.",
			Kind:          KindOption,
			ConflictsWith: []string{"--soft", "--hard", "--merge", "--keep", "--patch"},
		},
		{
			Value:         "--hard",
			Description:   "Reset HEAD, index, and working tree; uncommitted changes may be lost.",
			Kind:          KindOption,
			ConflictsWith: []string{"--soft", "--mixed", "--merge", "--keep", "--patch"},
		},
		{
			Value:         "--merge",
			Description:   "Reset the index and update files while preserving unmerged changes.",
			Kind:          KindOption,
			ConflictsWith: []string{"--soft", "--mixed", "--hard", "--keep", "--patch"},
		},
		{
			Value:         "--keep",
			Description:   "Reset HEAD while preserving local working tree changes.",
			Kind:          KindOption,
			ConflictsWith: []string{"--soft", "--mixed", "--hard", "--merge", "--patch"},
		},
		{
			Value:         "--patch",
			Description:   "Interactively select changes to reset.",
			Kind:          KindOption,
			Aliases:       []string{"-p"},
			ConflictsWith: []string{"--soft", "--mixed", "--hard", "--merge", "--keep"},
		},
		{
			Value:       "--quiet",
			Description: "Only report errors.",
			Kind:        KindOption,
			Aliases:     []string{"-q"},
		},
		{
			Value:       "--no-refresh",
			Description: "Do not refresh the index after resetting.",
			Kind:        KindOption,
		},
		{
			Value:            "--pathspec-from-file",
			Description:      "Read pathspec entries from a file.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "file",
			ValueDescription: "Enter a file containing pathspec entries.",
		},
		{
			Value:       "--pathspec-file-nul",
			Description: "Separate pathspec entries with NUL characters.",
			Kind:        KindOption,
		},
	},
	"revert": {
		{
			Value:       "--no-commit",
			Description: "Apply the inverse changes without creating a commit.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:         "--edit",
			Description:   "Edit the revert commit message before committing.",
			Kind:          KindOption,
			Aliases:       []string{"-e"},
			ConflictsWith: []string{"--no-edit"},
		},
		{
			Value:         "--no-edit",
			Description:   "Use the generated commit message without opening an editor.",
			Kind:          KindOption,
			ConflictsWith: []string{"--edit"},
		},
		{
			Value:            "--mainline",
			Description:      "Select the parent used when reverting a merge commit.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "parent-number",
			ValueDescription: "Enter the mainline parent number, usually 1 or 2.",
			Aliases:          []string{"-m"},
		},
		{
			Value:       "--signoff",
			Description: "Add a Signed-off-by trailer to the commit message.",
			Kind:        KindOption,
			Aliases:     []string{"-s"},
		},
		{
			Value:            "--strategy",
			Description:      "Use the specified merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "strategy",
			ValueDescription: "Enter a merge strategy.",
		},
		{
			Value:            "--strategy-option",
			Description:      "Pass an option to the selected merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "option",
			ValueDescription: "Enter a merge strategy option.",
			Repeatable:       true,
			Aliases:          []string{"-X"},
		},
		{
			Value:         "--continue",
			Description:   "Continue after resolving conflicts.",
			Kind:          KindOption,
			ConflictsWith: []string{"--skip", "--abort", "--quit"},
		},
		{
			Value:         "--skip",
			Description:   "Skip the current commit and continue.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--abort", "--quit"},
		},
		{
			Value:         "--abort",
			Description:   "Cancel the operation and restore the previous state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--quit"},
		},
		{
			Value:         "--quit",
			Description:   "Stop the operation without restoring the previous state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--abort"},
		},
	},
	"cherry-pick": {
		{
			Value:       "--no-commit",
			Description: "Apply changes without creating a commit.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:         "--edit",
			Description:   "Edit the commit message before committing.",
			Kind:          KindOption,
			Aliases:       []string{"-e"},
			ConflictsWith: []string{"--no-edit"},
		},
		{
			Value:         "--no-edit",
			Description:   "Use the original commit message without opening an editor.",
			Kind:          KindOption,
			ConflictsWith: []string{"--edit"},
		},
		{
			Value:            "--mainline",
			Description:      "Select the parent used when cherry-picking a merge commit.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "parent-number",
			ValueDescription: "Enter the mainline parent number, usually 1 or 2.",
			Aliases:          []string{"-m"},
		},
		{
			Value:       "--signoff",
			Description: "Add a Signed-off-by trailer to the commit message.",
			Kind:        KindOption,
			Aliases:     []string{"-s"},
		},
		{
			Value:            "--strategy",
			Description:      "Use the specified merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "strategy",
			ValueDescription: "Enter a merge strategy.",
		},
		{
			Value:            "--strategy-option",
			Description:      "Pass an option to the selected merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "option",
			ValueDescription: "Enter a merge strategy option.",
			Repeatable:       true,
			Aliases:          []string{"-X"},
		},
		{
			Value:       "-x",
			Description: "Append the original commit name to the commit message.",
			Kind:        KindOption,
		},
		{
			Value:       "--ff",
			Description: "Allow a fast-forward when possible.",
			Kind:        KindOption,
		},
		{
			Value:            "--empty",
			Description:      "Choose how commits that become empty are handled.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "mode",
			ValueDescription: "Enter stop, drop, or keep.",
		},
		{
			Value:         "--continue",
			Description:   "Continue after resolving conflicts.",
			Kind:          KindOption,
			ConflictsWith: []string{"--skip", "--abort", "--quit"},
		},
		{
			Value:         "--skip",
			Description:   "Skip the current commit and continue.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--abort", "--quit"},
		},
		{
			Value:         "--abort",
			Description:   "Cancel the operation and restore the previous state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--quit"},
		},
		{
			Value:         "--quit",
			Description:   "Stop the operation without restoring the previous state.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--abort"},
		},
	},
	"clean": {
		{
			Value:       "--quiet",
			Description: "Do not print the names of removed files.",
			Kind:        KindOption,
			Aliases:     []string{"-q"},
		},
		{
			Value:       "--dry-run",
			Description: "Show what would be removed without deleting anything.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--force",
			Description: "Allow removal of untracked files.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "--interactive",
			Description: "Interactively choose files to remove.",
			Kind:        KindOption,
			Aliases:     []string{"-i"},
		},
		{
			Value:       "-d",
			Description: "Remove untracked directories in addition to files.",
			Kind:        KindOption,
		},
		{
			Value:            "--exclude",
			Description:      "Add a pattern to the ignore rules used by clean.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "pattern",
			ValueDescription: "Enter a pattern that should not be removed.",
			Repeatable:       true,
			Aliases:          []string{"-e"},
		},
		{
			Value:         "-x",
			Description:   "Remove ignored files as well as untracked files.",
			Kind:          KindOption,
			ConflictsWith: []string{"-X"},
		},
		{
			Value:         "-X",
			Description:   "Remove only ignored files.",
			Kind:          KindOption,
			ConflictsWith: []string{"-x"},
		},
	},
	"rm": {
		{
			Value:       "--dry-run",
			Description: "Show files that would be removed without removing them.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--quiet",
			Description: "Do not print the names of removed files.",
			Kind:        KindOption,
			Aliases:     []string{"-q"},
		},
		{
			Value:       "--cached",
			Description: "Remove paths only from the index and keep working tree files.",
			Kind:        KindOption,
		},
		{
			Value:       "--force",
			Description: "Override the up-to-date check.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "-r",
			Description: "Allow recursive removal of directories.",
			Kind:        KindOption,
		},
		{
			Value:       "--ignore-unmatch",
			Description: "Exit successfully even when no path matches.",
			Kind:        KindOption,
		},
		{
			Value:       "--sparse",
			Description: "Allow updating entries outside the sparse-checkout cone.",
			Kind:        KindOption,
		},
		{
			Value:            "--pathspec-from-file",
			Description:      "Read pathspec entries from a file.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "file",
			ValueDescription: "Enter a file containing pathspec entries.",
		},
		{
			Value:       "--pathspec-file-nul",
			Description: "Separate pathspec entries with NUL characters.",
			Kind:        KindOption,
		},
	},
	"mv": {
		{
			Value:       "--verbose",
			Description: "Print the names of files as they are moved.",
			Kind:        KindOption,
			Aliases:     []string{"-v"},
		},
		{
			Value:       "--dry-run",
			Description: "Show what would be moved without changing files.",
			Kind:        KindOption,
			Aliases:     []string{"-n"},
		},
		{
			Value:       "--force",
			Description: "Allow an existing destination to be overwritten.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "-k",
			Description: "Skip paths that cannot be moved or renamed.",
			Kind:        KindOption,
		},
		{
			Value:       "--sparse",
			Description: "Allow updating entries outside the sparse-checkout cone.",
			Kind:        KindOption,
		},
	},
	"rebase": {
		{
			Value:            "--onto",
			Description:      "Rebase commits onto a different base.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "revision",
			ValueDescription: "Enter the new base branch, tag, or commit.",
			ConflictsWith:    []string{"--keep-base"},
		},
		{
			Value:         "--keep-base",
			Description:   "Use the merge base of upstream and branch as the base.",
			Kind:          KindOption,
			ConflictsWith: []string{"--onto"},
		},
		{
			Value:       "--interactive",
			Description: "Edit the list of commits before rebasing.",
			Kind:        KindOption,
			Aliases:     []string{"-i"},
		},
		{
			Value:            "--exec",
			Description:      "Run a command after each rebased commit.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "command",
			ValueDescription: "Enter the shell command to execute.",
			Repeatable:       true,
			Aliases:          []string{"-x"},
		},
		{
			Value:         "--autosquash",
			Description:   "Reorder fixup! and squash! commits during interactive rebase.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-autosquash"},
		},
		{
			Value:         "--no-autosquash",
			Description:   "Do not reorder fixup! and squash! commits.",
			Kind:          KindOption,
			ConflictsWith: []string{"--autosquash"},
		},
		{
			Value:         "--autostash",
			Description:   "Temporarily stash local changes before rebasing.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-autostash"},
		},
		{
			Value:         "--no-autostash",
			Description:   "Do not automatically stash local changes.",
			Kind:          KindOption,
			ConflictsWith: []string{"--autostash"},
		},
		{
			Value:         "--update-refs",
			Description:   "Update branches that point to rebased commits.",
			Kind:          KindOption,
			ConflictsWith: []string{"--no-update-refs"},
		},
		{
			Value:         "--no-update-refs",
			Description:   "Do not update other branches pointing to rebased commits.",
			Kind:          KindOption,
			ConflictsWith: []string{"--update-refs"},
		},
		{
			Value:         "--rebase-merges",
			Description:   "Preserve merge commits while rebasing.",
			Kind:          KindOption,
			Aliases:       []string{"-r"},
			ConflictsWith: []string{"--apply"},
		},
		{
			Value:       "--root",
			Description: "Rebase all reachable commits starting from the root.",
			Kind:        KindOption,
		},
		{
			Value:            "--empty",
			Description:      "Choose how commits that become empty are handled.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "mode",
			ValueDescription: "Enter drop, keep, or stop.",
		},
		{
			Value:         "--apply",
			Description:   "Use the apply backend for the rebase.",
			Kind:          KindOption,
			ConflictsWith: []string{"--merge", "--rebase-merges"},
		},
		{
			Value:         "--merge",
			Description:   "Use merge strategies instead of applying patches.",
			Kind:          KindOption,
			Aliases:       []string{"-m"},
			ConflictsWith: []string{"--apply"},
		},
		{
			Value:            "--strategy",
			Description:      "Use the specified merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "strategy",
			ValueDescription: "Enter a merge strategy.",
			Aliases:          []string{"-s"},
		},
		{
			Value:            "--strategy-option",
			Description:      "Pass an option to the selected merge strategy.",
			Kind:             KindOption,
			TakesValue:       true,
			ValueName:        "option",
			ValueDescription: "Enter a merge strategy option.",
			Repeatable:       true,
			Aliases:          []string{"-X"},
		},
		{
			Value:       "--force-rebase",
			Description: "Replay every commit even when it appears unchanged.",
			Kind:        KindOption,
			Aliases:     []string{"-f"},
		},
		{
			Value:       "--signoff",
			Description: "Add a Signed-off-by trailer to each rebased commit.",
			Kind:        KindOption,
		},
		{
			Value:       "--no-verify",
			Description: "Bypass the pre-rebase hook.",
			Kind:        KindOption,
		},
		{
			Value:         "--continue",
			Description:   "Continue after resolving conflicts.",
			Kind:          KindOption,
			ConflictsWith: []string{"--skip", "--abort", "--quit", "--edit-todo", "--show-current-patch"},
		},
		{
			Value:         "--skip",
			Description:   "Skip the current commit and continue.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--abort", "--quit", "--edit-todo", "--show-current-patch"},
		},
		{
			Value:         "--abort",
			Description:   "Cancel the rebase and restore the original branch.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--quit", "--edit-todo", "--show-current-patch"},
		},
		{
			Value:         "--quit",
			Description:   "Stop rebasing without restoring the original branch.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--abort", "--edit-todo", "--show-current-patch"},
		},
		{
			Value:         "--edit-todo",
			Description:   "Edit the todo list of an interactive rebase.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--abort", "--quit", "--show-current-patch"},
		},
		{
			Value:         "--show-current-patch",
			Description:   "Show the patch currently being applied.",
			Kind:          KindOption,
			ConflictsWith: []string{"--continue", "--skip", "--abort", "--quit", "--edit-todo"},
		},
	},
}
